[project]
name = "target-intacct"
version = "0.1.0"
description = "`target-intacct` is a Singer target for Intacct, built with the Meltano SDK for Singer Targets."
authors = [{ name = "Hotglue", email = "hello@hotglue.io" }]
keywords = [
    "ELT",
    "intacct",
]
license = "Apache-2.0"
requires-python = "<3.11,>=3.7.1"
dependencies = [
    "requests>=2.25.1",
    "hotglue-singer-sdk>=1.0.11",
    "hotglue-models-accounting @ git+https://gitlab.com/hotglue/hotglue-models-accounting.git@v2",
    "xmltodict>=0.12.0",
]

[project.scripts]
target-intacct = 'target_intacct.target:TargetIntacct.cli'

[dependency-groups]
dev = [
    "pytest>=7",
    "ruff>=0.15",
]

[tool.ruff]
line-length = 100
required-version = ">=0.15"

[tool.ruff.lint]
future-annotations = true
ignore = [
    "COM812",
    "FIX002",
    "TD002",
    "TD003",
]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
  "D103",
  "CPY001",
  "PLR2004",
  "PT018",
]
"target_intacct/client.py" = [
    "ANN401",
    "D102",
    "I001",
]
"target_intacct/sinks.py" = [
    "D102",
    "I001",
    "TRY003",
    "EM101",
    "EM102",
    "ARG002",
    "CPY001",
]
"target_intacct/xml_client.py" = [
    "ANN401",
    "D102",
    "D107",
    "CPY001",
    "TRY003",
    "EM101",
    "EM102",
    "PLR2004",
    "TC003",
]
"target_intacct/bank_reconciliation.py" = [
    "ANN401",
    "CPY001",
    "TRY003",
    "EM101",
    "EM102",
    "PLR2004",
    "PLR0913",
    "TC003",
    "DTZ007",
]
"target_intacct/mappers/*.py" = [
    "ANN401",
    "CPY001",
    "D107",
    "TRY003",
    "EM101",
    "EM102",
    "PLR2004",
]
"target_intacct/target.py" = [
    "RUF012",
    "I001",
    "CPY001",
    "E501",
    "ANN001",
    "ANN206",
    "ARG003",
    "D102",
    "F401",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
